# Generated by Django 4.1 on 2023-09-11 15:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, unique=True, verbose_name='用語')),
                ('explanation', models.TextField(verbose_name='説明')),
                ('picture', models.FileField(blank=True, upload_to='picture/', verbose_name='画像')),
                ('update_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '用語',
                'verbose_name_plural': '用語',
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name='コメント')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.terms', verbose_name='用語')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'db_table': 'comments',
            },
        ),
    ]
