# Generated by Django 4.1 on 2023-10-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='update_user',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='最終更新者'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=1000, verbose_name='返信')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.comments', verbose_name='コメント')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '返信',
                'verbose_name_plural': '返信',
                'db_table': 'replys',
            },
        ),
    ]
