# Generated by Django 4.1 on 2023-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_terms_update_user_alter_comments_user_replys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/', verbose_name='画像'),
        ),
    ]
